language: java
jdk: oraclejdk11
cache:
  directories:
  - $HOME/.m2
install: true
jobs:
  include:
    - stage: test
      script:
        - mvn clean verify
    - stage: deploy
      script:
        - mvn clean package
stages:
  - name: test
    if: type = push
  - name: deploy
    if: type = pull_request